### ISSUE TITLE
可以简单解释下weibo文件夹下的文件含义吗

### ISSUE THREAD

**Issue by wanglii** [SixingPKU/ACL2020-ConKADI#1]
您好，datasets/weibo下面的文件非常多，不太清楚文件是怎么生成的，文件内容代表什么，可以麻烦您写个简单的每个文件的介绍，介绍下文件格式吗？
另外，您生成这些预处理文件的代码方便分享出来吗
非常感谢

**Comment by pku-sixing** [comment]
你好，这些东西随后会更新的，因为实验赶得比较急，代码总体比较杂乱所以没有第一时间一起整理公布。

后续会提供数据说明的，但因为最近比较忙，可能需要一点时间，我尽快。
