### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by xiao-ming-code** [SixingPKU/ACL2020-ConKADI#7]
Hello, I made the following error when executing the Reddit training command (the first picture), then I changed & to 2>&1 &, and did not train, I would like to ask what happened? I don't think there was any training.
![VJ )L%Y)$M}P9_RO%0%Y(U8](https://user-images.githubusercontent.com/73177290/145990380-9a7548e1-274b-4f60-8ecb-9d37b8fa10ff.png)
![3 T9MR5PS9R8$VGPMBP4ZKX](https://user-images.githubusercontent.com/73177290/145990421-3d93b226-f954-41db-8e94-66928ef4f2de.png)

**Comment by pku-sixing** [comment]
Hi,

In the provided instruction/script, the running log has been redirected to logs/xxx.txt.  For example, in your first pic, you can find the log in logs/reddit.txt. To see the detail, please check the corresponding log file.

or you can remove `nohup' and '>> ............&', thus you can see the detail when you execute this command.

I think the log file can help you much.

**Comment by xiao-ming-code** [comment]
Thank you very much. I deleted it and carried out the training smoothly. However, I still can't solve the following mistakes.
![)8EUDPPYC@VYT WGY_XUIYI](https://user-images.githubusercontent.com/73177290/145999653-b7a787b9-5201-40e6-a0e5-15d1dc79a4fc.png)

![F@0VRJ2T%$F4PX_JDQLIMSM](https://user-images.githubusercontent.com/73177290/145999589-5ff71bcd-586a-48c2-aa3b-bc39eff7a62b.png)

**Comment by xiao-ming-code** [comment]
Why are you so slow to get started? I set CUDA_VISIBLE_DEVICES=0, but it's still slow

**Comment by pku-sixing** [comment]
I think your tensorflow is not compatible with this code.

Did you use the same tensorflow version? 

If you use the provided config, please make sure the same version, and the same backend (tensorflow-gpu).

**Comment by xiao-ming-code** [comment]
Yes, I have installed tensorflow-gpu=1.14.0, my CUDA is 11.4, will it be incompatible?

**Comment by xiao-ming-code** [comment]
Is there any other version of TensorFlow that I would recommend to try?

**Comment by pku-sixing** [comment]
My CUDA is 10.1, and  GPU is RTX 2080Ti. 

I tested this code with a newly created Conda environment.  You can try to use the same method.

Currently, I have turned to PyTorch, so there is no recommendation for other versions of tensorflow.

**Comment by xiao-ming-code** [comment]
Thank you very much. I also use PyTorch, but I am not familiar with TenforFlow. Is there a PyTorch version of the code implemented in this paper?

**Comment by pku-sixing** [comment]
Sorry, no other implementation. The only way is to find a similar environment. 

Meanwhile, please use the default configs to verify your environment if you can successfully run this code.

The running has randomness, but the result should be close to the reported (3) scores.

**Comment by xiao-ming-code** [comment]
Thank you very much
I successfully ran the code using Tensorflow-GPU =1.15.0
But it runs very slowly. I checked the gpu usage, and it hardly occupies any space. Do you have any idea what the problem might be?I set  code export  CUDA_VISIBLE_DEVICES=0

**Comment by xiao-ming-code** [comment]
Trouble,
Where is the gpu location in the code?
Why am I running on a CPU?
but tf.test.is_built_with_cuda()=True

**Comment by xiao-ming-code** [comment]
Excuse me, by the way,
Where is the gpu location in the code?
Why am I running on a CPU?
but tf.test.is_built_with_cuda()=True

**Comment by pku-sixing** [comment]
By default, this code will use GPU with tensorflow-gpu 1.14.0. 

There is no code to control the usage of GPU.  CUDA_VISIBLE_DEVICES=0 is used to assign a gpu, it is not necessary. and you can change to another available GPU id.

After you execute this code,  you can use `nvidia-smi' to check the GPU usage.

**Comment by pku-sixing** [comment]
I tested this code in a new Conda environment,  and the code/script could use my GPU automatically.
